name: Deployment BrightUzbekistan Client
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server
        uses: appleboy/ssh-action@main
        with:
          host: 185.74.5.188
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/user/getter/bright-client
            git pull origin main
            git status
            npm install --yes
            rm -rf .next
            npm run build
            pm2 restart bright-client